name: 'Date Action CI'
description: 'Gets the date of the last time the CI was passed. There are different formats, which you upload to gist and then use it in a badge inside your README.md file or other files where you want to display it.. Inspired in of https://github.com/Schneegans/dynamic-badges-action'
author: 'Juan Carlos Manzanares Serrano'

inputs:
  gist_id:
    description: 'Gist ID of the repository where your file is located'
    requred: true
  gist_token:
    description: 'Token generated on github with access to gist'
    required: true
  gist_filename:
    description: 'Name of the file hosted in gist'
    required: false
    default: date.json
  color:
    description: 'Color for the badge'
    required: false
    default: 'blue'
  show_year:
    description: 'The year is displayed in the date message'
    required: false
    default: true
  show_month:
    description: 'The month is displayed in the date message'
    required: false
    default: true
  show_day:
    description: 'The day number is displayed in the date message'
    required: false
    default: true
  show_hour:
    description: 'The hour with minutes is displayed in the date message'
    required: false
    default: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.color }}
    - ${{ inputs.show_year }}
    - ${{ inputs.show_month }}
    - ${{ inputs.show_day }}
    - ${{ inputs.show_hour }}
    - ${{ inputs.gist_id }}
    - ${{ inputs.gist_token }}
    - ${{ inputs.gist_filename }}